### PR TITLE
Feature! manager upgrade!

### PR DESCRIPTION
**Pull request by M3TIOR**
Now ya don't have to manage migrations...

Just use:
```
manage.py upserver
```

woohoo!

### CODE REVIEW

**Comment by apachano** [comment]
Okay how am I supposed to clone this and test it,

**Comment by M3TIOR** [comment]
https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch
 **In case you want to read it yourself**

```
# or just do this.
git fetch
git checkout feature---manager-upgrade
```

**Comment by apachano** [comment]
image

**Comment by apachano** [comment]
image

**Comment by M3TIOR** [comment]
... you fetched twice...
`git checkout feature---manager-upgrade`

**Comment by apachano** [comment]
SQL is a pain in the ass, Django is a pain in the ass, I cant get the website to go to the servers page here is the error. (1054, "Unknown column 'servers_tag.value' in 'field list'")

There is a lot of code you have worked on in different areas. its a lot to look though can you split it into parts so I can test and accept them easier. I could probably accept all the testing code so we can focus on the big changes separately. 

Also note, I am not good with git either.

**Comment by M3TIOR** [comment]
I can absolutely split my work into smaller commits. But it won't fix the problem you're currently having. Did you try using `manage.py upserver`? or the fix I mentioned previously in pull request #7? 

Just so you don't have to go back here's the alternate solution again. (as in outside of executing `manage.py upserver`)
```
manage.py makemigrations servers #<<THE NAME OF THE DJANGO APP
manage.py migrate
manage.py runserver
```

**Comment by apachano** [comment]
image

I also tried making migrations, I put the log on pastebin

https://pastebin.com/d4ihvJUg

**Comment by M3TIOR** [comment]
Did you have your sql server up while you were trying to make the migrations? The traceback show's the reason makemigrations failed was because it couldn't connect.

**Comment by apachano** [comment]
image
image

**Comment by M3TIOR** [comment]
by best advice to you then would be to make a new sql database...

**Comment by apachano** [comment]
Nope, same error, really fucking irritating. I also deleted the entire database and let it rebuild it and get the same error. Please make sure all of the code is 100% up to date on this repository (Double check by pulling a zip file). I am going to try pulling again when I get off work tonight. If that fails I am going to ask you to send me a zip file with the code in it. Double check it work with a fresh pull on your end as well please.

Here is a snip showing my current branch just to verify I am on the right one.
image

**Comment by M3TIOR** [comment]
So... I did find out why you can't use `upserver`... Literally one line I forgot to commit.

But still, that SQL error is a real problem. Everything I've had you do should have fixed it. `upserver` just does the three commands that I gave you in order anyway. So I don't think running that will fix your problem at this point. Still, might as well give it a shot. And since It's probably not going to fix anything, how do you want to transport the zip file?

**Comment by apachano** [comment]
SQL is a pain

**Comment by apachano** [comment]
You still did break some things but they are easy to fix and I am also mad at git so I am not going to mess with this pull request bull

**Comment by M3TIOR** [comment]
Okay.

**Comment by M3TIOR** [comment]
Does that mean you don't want me to contribute anymore? Using the fork & pull system is the safest for managing external contributors.  ¯\_(ツ)_/¯

**Comment by apachano** [comment]
I do, I need the help, I am just pissed at github and sql for being extra special pains in the ass

**Comment by apachano** [comment]
So far besides screwing with djangos preferred formatting and you didnt add anything tot he admin panel so I have to add those its fine now. Mostly SQL being annoying. I am going to make some fixes and push them to master.

**Comment by M3TIOR** [comment]
Ok

**Comment by apachano** [comment]
This line is causing issues, what is its purpose?
servers/views.py:59
`model = form.save(commit=False)`

**Comment by apachano** [comment]
I found a work around but why is it there

**Comment by M3TIOR** [comment]
IDK, I'm thinking it's there to initialize the new form data before instantiation. But I could be wrong. I assumed you wrote it...

**Pull request merged**
